03:20:06.681 [Thread-2] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskCommunicator - Failed to send state update to node: host1:15002, Killing all attempts running on node. Attempted StateUpdate=query_identifier {
  application_id_string: "application_1000_0001"
  dag_index: 200
  app_attempt_number: 100
}
src_name: "vertexName1"
state: S_SUCCEEDED

java.io.IOException: Force failing host1
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskCommunicator$FinishableStatusUpdateTestAnswer$1.run(TestLlapTaskCommunicator.java:224) [test-classes/:?]
org.junit.runners.model.TestTimedOutException: test timed out after 10000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.forTestAwaitSchedulingRun(TestLlapTaskSchedulerService.java:2366)
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$TestTaskSchedulerServiceWrapper.awaitSchedulerRun(TestLlapTaskSchedulerService.java:2108)
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$TestTaskSchedulerServiceWrapper.<init>(TestLlapTaskSchedulerService.java:2092)
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$TestTaskSchedulerServiceWrapper.<init>(TestLlapTaskSchedulerService.java:2024)
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$TestTaskSchedulerServiceWrapper.<init>(TestLlapTaskSchedulerService.java:2018)
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService.testAdjustLocalityDelay(TestLlapTaskSchedulerService.java:913)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
03:20:16.805 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
03:20:16.829 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
03:20:16.856 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
03:20:16.879 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
03:20:16.909 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
03:20:16.932 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
03:20:19.008 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
03:20:19.031 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
03:20:19.052 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
03:20:19.070 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
03:20:21.109 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
03:20:21.124 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
03:20:21.139 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
03:20:21.152 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
03:20:21.203 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
03:20:21.224 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
03:20:21.240 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
03:20:21.294 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
03:20:21.318 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
03:20:21.331 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
03:20:22.447 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
03:20:22.462 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
