00:57:56.551 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
00:57:56.585 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
00:57:56.604 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
00:57:56.635 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
00:57:56.655 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
00:57:56.681 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
00:57:56.700 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
00:57:58.766 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
00:57:58.789 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
00:57:58.819 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
00:57:58.835 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
00:58:00.884 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
00:58:00.898 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
00:58:00.914 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
00:58:00.927 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
00:58:00.961 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
00:58:00.979 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
00:58:00.994 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
00:58:01.045 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
00:58:01.065 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
00:58:01.079 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
00:58:02.156 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
00:58:02.168 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
00:58:02.397 [Thread-2] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskCommunicator - Failed to send state update to node: host1:15002, Killing all attempts running on node. Attempted StateUpdate=query_identifier {
  application_id_string: "application_1000_0001"
  dag_index: 200
  app_attempt_number: 100
}
src_name: "vertexName1"
state: S_SUCCEEDED

java.io.IOException: Force failing host1
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskCommunicator$FinishableStatusUpdateTestAnswer$1.run(TestLlapTaskCommunicator.java:224) [test-classes/:?]
