03:22:29.914 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
